// mock-data.js - Dados Iniciais da Plataforma SolidarAção

window.INITIAL_DATA = {
  pontos: [
    {
      id: 1,
      code: 'SA-1001',
      nome: 'Ajude a Alimentar 200 Famílias — Cestas Básicas de Emergência',
      title: 'Ajude a Alimentar 200 Famílias — Cestas Básicas de Emergência',
      endereco: 'Bairro Centenário — Aracati',
      bairro: 'Centenário',
      contato: '(88) 99123-4567',
      responsavel: 'ONG Esperança Viva',
      creator_name: 'ONG Esperança Viva',
      is_verified: true,
      categorias: ['alimentos'],
      category: 'alimentos',
      statusEstoque: { alimentos: 'critico' },
      descricao: 'Estamos arrecadando cestas básicas e recursos para garantir alimentação completa de 200 famílias periféricas que enfrentam extrema vulnerabilidade alimentar.',
      description: 'Estamos arrecadando cestas básicas e recursos para garantir alimentação completa de 200 famílias periféricas que enfrentam extrema vulnerabilidade alimentar.',
      target_amount: 15000.00,
      current_amount: 8450.00,
      target_items: 200,
      current_items: 112,
      unit: 'cestas',
      image_url: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&auto=format&fit=crop&q=80',
      location: 'Aracati - CE',
      horario: 'Atendimento contínuo'
    },
    {
      id: 2,
      code: 'SA-1002',
      nome: 'Campanha do Agasalho e Cobertores — Inverno Sem Fome',
      title: 'Campanha do Agasalho e Cobertores — Inverno Sem Fome',
      endereco: 'Centro — Aracati',
      bairro: 'Centro',
      contato: '(88) 98877-6655',
      responsavel: 'ONG Mãos Unidas',
      creator_name: 'ONG Mãos Unidas',
      is_verified: true,
      categorias: ['roupas'],
      category: 'roupas',
      statusEstoque: { roupas: 'critico' },
      descricao: 'Arrecadação de agasalhos de frio, roupas infantis e cobertores grossos para famílias e albergados durante as baixas temperaturas.',
      description: 'Arrecadação de agasalhos de frio, roupas infantis e cobertores grossos para famílias e albergados durante as baixas temperaturas.',
      target_amount: 8000.00,
      current_amount: 5200.00,
      target_items: 300,
      current_items: 195,
      unit: 'peças',
      image_url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop&q=80',
      location: 'Aracati - CE',
      horario: 'Seg a Sáb: 08h às 18h'
    },
    {
      id: 3,
      code: 'SA-1003',
      nome: 'Kit Higiene Pessoal e Proteção',
      title: 'Kit Higiene Pessoal e Proteção',
      endereco: 'Centro — Aracati',
      bairro: 'Victor Konder',
      contato: '(88) 99911-2233',
      responsavel: 'Instituto Proteja',
      creator_name: 'Instituto Proteja',
      is_verified: true,
      categorias: ['higiene'],
      category: 'higiene',
      statusEstoque: { higiene: 'moderado' },
      descricao: 'Compra e distribuição de kits contendo fraldas descartáveis, sabonete infantil, creme dental, absorventes e produtos de higiene essenciais.',
      description: 'Compra e distribuição de kits contendo fraldas descartáveis, sabonete infantil, creme dental, absorventes e produtos de higiene essenciais.',
      target_amount: 6000.00,
      current_amount: 3800.00,
      target_items: 150,
      current_items: 95,
      unit: 'kits',
      image_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
      location: 'Aracati - CE',
      horario: 'Diariamente: 08h às 17h'
    }
  ],
  metas: [],
  agendamentos: [],
  mensagens: []
};
